services:
  postgres:
    image: postgres:16
    container_name: my_subscription_postgres

    environment:
      POSTGRES_USER: aj_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: aj_subscription
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.22
    container_name: my_subscription_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
